### ISSUE TITLE
rule-based styling to relationship

### ISSUE THREAD

**Issue by seonyh0** [neo4j-labs/neodash#283] opened 2022-12-06 00:38 UTC
For v2.2 rule-based styling, only node color and node label color can be applied.
Is it possible to apply the color and thickness of the relationship according to the type of the relationship ?
If not, I would like to know when you plan to apply it.

**Comment by BennuFire** [comment] 2022-12-07 14:51
Hi @seonyh0 !

At the moment, this is not possible. It's a good request tho, it will not make next release (scheduled this week) but it can be part of one last release before the end of the year :D

**Comment by brahmprakashMishra** [comment] 2023-06-07 09:44
I am shortly going to make a PR about this. Seems to be a duplicate of another issue though - maybe we should triage the issues?

**Comment by brahmprakashMishra** [comment] 2023-06-09 18:48
https://github.com/neo4j-labs/neodash/pull/481/files 

I have made a PR regarding this feature that allows customisation of relationship colors using the json config.

**Comment by bastienhubert** [comment] 2023-07-14 12:48
Hey @brahmprakashMishra, thanks for the PR! 

I will rework a bit on it to make it usable directly through the UI.

**Comment by adriens** [comment] 2023-07-14 20:30
Awesome, there are so many use cases around here :pray:

**Closed** 2023-08-16 06:49 UTC
Labels: good first issue
