### ISSUE TITLE
Dashboard tabs not opening when clicked, tab name swapping

### ISSUE THREAD

**Issue by prakritiarya** [neo4j-labs/neodash#739] opened 2023-12-20 10:37 UTC
- NeoDash version: 2.2.1
- Neo4j Database version: 4.4.8 (Enterprise)

- Expected behaviour: When the user clicks on any tab, the respective page should open
- Actual behaviour : **When clicking on any tab, the respective page does not open, just the tabs swap their names with other tabs**, not working in correct manner.

No issues/errors in docker image deployment, only warnings related to react version and node.js versions. 

Any ideas why?

**Comment by nielsdejong** [comment] 2024-01-04 14:23
hi @prakritiarya ,
I'm not able to reproduce this issue on the latest version (2.4.1).
Could you try upgrading to that version? Also, which browser are you using? For me it's all working well on Chrome/Firefox.

**Comment by prakritiarya** [comment] 2024-01-09 05:25
Hi @nielsdejong 
this issue is present in version 2.2.1 with browsers like chrome/safari/edge , although could not resolve it with the same version, so upgraded the version to 2.4.1 and its resolved now. 
Thanks

**Comment by nielsdejong** [comment] 2024-01-09 07:53
Thanks @prakritiarya ! Closing this issue

**Closed by nielsdejong** 2024-01-09 07:53 UTC
Labels: bug
